name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main, stage]
  pull_request:
    branches: [main, stage]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

env:
  PAGE_ENV: ${{ github.ref_name == 'main' && 'production' || 'staging'}}

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' && github.ref_name != 'stage' }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        shell: "bash"
        working-directory: .
        run: npm install
      - name: Check
        shell: "bash"
        working-directory: .
        run: npm run check

  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' || github.ref_name == 'stage' }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'stage' }}
    env:
      SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install -g surge
      - uses: actions/download-artifact@v3
        with:
          name: github-pages
      - name: Extract tar and delete the tar and display structure of downloaded files
        run: tar -xvf artifact.tar && rm artifact.tar && ls -R
      - name: Deploy to surge.sh
        run: surge . ${{ env.SURGE_DOMAIN }} --token ${{ env.SURGE_TOKEN }}
